language: scala
dist: trusty
group: edge
scala:
  - 2.12.3
jdk:
  - oraclejdk8
node_js:
  - "6"

script:
  - SBT_PROFILE=coverage sbt clean coverage test coverageReport coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
  - sbt clean test

